# Generated by Django 4.2.3 on 2023-07-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_stage_remove_fighter_series_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('fighter_style', models.CharField(max_length=100)),
                ('move_set', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('series_name', models.CharField(max_length=100)),
            ],
        ),
    ]
