# Generated by Django 4.2.3 on 2023-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fighter_style',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='image',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='move_set',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='series_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='image',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='series_name',
            field=models.TextField(max_length=100),
        ),
    ]
