# Generated by Django 4.2.3 on 2023-07-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('series_name', models.CharField(max_length=100)),
                ('fighter_style', models.CharField(max_length=100)),
                ('move_set', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('series_id', models.IntegerField()),
            ],
        ),
    ]
