# Generated by Django 4.2.3 on 2023-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('series_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='series_id',
        ),
    ]
